server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/indentity.service"
    username: root
    password: 17102002
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
